### ISSUE TITLE
HIGH PRIORITY ::::  TODO list for final presentation

### ISSUE THREAD

**Issue by glaubernespoli** [glaubernespoli/dci-final-project-frontend#86]
========================================================
HIGH PRIORITY!!! LETS FIX THOSE BEFORE THE FINAL PRESENTATION
- [x] #88
- [x] #92
- [x] #87
      -> Solution 1 (cooler, but more work): Two different image fields, lets say imageUrl (the one we have right now) and carouselUrl - the second one being a canvas composed of the original image + some hightlight text (to grab attention)
      -> Solution 2 (less cool, but much easier): Have the carousel still be a rectangle, put some background color on it (some different shade of dark color) and have the image be on the center as a square

![image](https://user-images.githubusercontent.com/7003334/124581452-68fc1400-de51-11eb-8bbc-9b4726791c46.png)

- [x] #89

![image](https://user-images.githubusercontent.com/7003334/124581637-8fba4a80-de51-11eb-9b3f-153530a191e3.png)

- [ ] #95
- [x] #90
![image](https://user-images.githubusercontent.com/7003334/124582270-2be45180-de52-11eb-8d81-0488c078062a.png)

- [x] #91
- [ ] Quantity as a field for the item: it also needs to be shown on the product item page

ADMIN FEATURES:

- [ ] Connection with Discogs
- [ ] Admin dashboard should use data from the logged user, not static data
![image](https://user-images.githubusercontent.com/7003334/124583528-6dc1c780-de53-11eb-974e-57a84a59e6d8.png)

- [x] #100

========================================================
PRESENTATION

- [x] Less text! More 'topics' (about our project, problem description and motivation)
- [x] Technologies: remove the basic logos (js). add: express, auth0, jwt, eslint
- [x] Technologies/features used: less time, no need to go into details about each of those small libraries. Try to rework in a way that makes it more appealing (remove redundant citations, like - material ui with react 5, material ui carousel, parallax effect to be simply MaterialUI) , routing blablablablabla to be just React Routers, Admin Dashboard to Admin Dashboard template XXX, cors
- [x] Functions and features: remove all the text, this slide we just go to the live presentation
- [x] Challenges and learning: dont mention things like materialui 5 or react-router-dom 6, be more abroad and mention like 'learning new and updated libraries', 'learning the rules and how to use materialUI', 'learning how to solve problems and searching for available solutions', 'learning the flows of react with state management using context and  the usage of hooks, both existing hooks and customized ones', learning how to write standardized and professional code between members of our project with eslint', (my personal add to challenges: TIMING)
- [x] maybe split challenge <--> learnings?
- [x] Future: describe our future plans for the application >>> integrate it with other platforms, not only discogs >>> mobile app
- [ ] decide who says each slide (we can write down and maybe on monday we do a test presentation between ourselves)

========================================================
COOL THINGS THAT WOULD BE COOL TO HAVE

- [x] Profile Page!!!
- [ ] NavBar menu items are also not responsive. when on mobile, the subitems dont work
